"""create ops ingestion run table

Revision ID: 68aa344626f2
Revises: a2ca88b4957b
Create Date: 2026-07-23 20:31:22.267564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68aa344626f2'
down_revision: Union[str, Sequence[str], None] = 'a2ca88b4957b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_succeeded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('connector_version', sa.String(length=100), nullable=True),
    sa.CheckConstraint('records_failed >= 0', name=op.f('ck_ingestion_run_records_failed_non_negative')),
    sa.CheckConstraint('records_received >= 0', name=op.f('ck_ingestion_run_records_received_non_negative')),
    sa.CheckConstraint('records_succeeded >= 0', name=op.f('ck_ingestion_run_records_succeeded_non_negative')),
    sa.ForeignKeyConstraint(['source_id'], ['ops.source.id'], name=op.f('fk_ingestion_run_source_id_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_run')),
    schema='ops'
    )
    op.create_index(op.f('ix_ingestion_run_source_id'), 'ingestion_run', ['source_id'], unique=False, schema='ops')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_run_source_id'), table_name='ingestion_run', schema='ops')
    op.drop_table('ingestion_run', schema='ops')
    # ### end Alembic commands ###
