"""create raw source payload table

Revision ID: f67768883d74
Revises: 496a2dd43058
Create Date: 2026-07-24 09:18:14.946261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f67768883d74'
down_revision: Union[str, Sequence[str], None] = '496a2dd43058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_payload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=False),
    sa.Column('external_record_id', sa.String(length=255), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint('http_status IS NULL OR (http_status >= 100 AND http_status <= 599)', name=op.f('ck_source_payload_http_status_valid')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ops.ingestion_run.id'], name=op.f('fk_source_payload_ingestion_run_id_ingestion_run'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['ops.source.id'], name=op.f('fk_source_payload_source_id_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_payload')),
    sa.UniqueConstraint('source_id', 'external_record_id', 'payload_hash', name='source_external_id_payload_hash'),
    schema='raw'
    )
    op.create_index('ix_source_payload_ingestion_run_id', 'source_payload', ['ingestion_run_id'], unique=False, schema='raw')
    op.create_index('ix_source_payload_source_retrieved_at', 'source_payload', ['source_id', 'retrieved_at'], unique=False, schema='raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_payload_source_retrieved_at', table_name='source_payload', schema='raw')
    op.drop_index('ix_source_payload_ingestion_run_id', table_name='source_payload', schema='raw')
    op.drop_table('source_payload', schema='raw')
    # ### end Alembic commands ###
